### ISSUE TITLE
Dockerfile on Ubuntu

### ISSUE THREAD

**Issue by lwassermann** [LivelyKernel/lively-docker#1]
Hello Robert,
I managed to use the docker file under Ubuntu Linux. Here are some remarks:
In the general installation instruction, you should `cd lively-docker` after cloning this repository.

The Dockerfile did not actually build for me. I had to comment out the `ADD objects.sqlite /var/www/...`-line in order to run them successfully. After that, and with running as root, it worked.

It seems that in Linux, all docker command have to be run as root. There are instructions to allow normal users to access the docker service, but those end up giving the user root access to the specific socket file to talk to the root-running daemon. It took me some time to understand that.

**Comment by rksm** [comment]
Thanks, should be fixed
