### ISSUE TITLE
repository dockerfile/nodejs not found (404)

### ISSUE THREAD

**Issue by kansasSamurai** [LivelyKernel/lively-docker#3]
Admittedly I am pretty new to Docker but I am able to create other containers.  Following your current instructions, I get the following:
$ sudo docker build --rm -t lively-server .
Sending build context to Docker daemon 149.5 kB
Sending build context to Docker daemon 
Step 0 : FROM          dockerfile/nodejs
Pulling repository dockerfile/nodejs
2015/09/27 17:18:07 HTTP code: 404

Forgive me if this is a fundamental troubleshooting issue; I can say that my machine is able to navigate the internet via browsers, ping, etc. so I am left only to believe that dockerfile/nodejs is unavailable.

**Comment by rksm** [comment]
Sorry, took a while. Should be fixed now
